<a href="https://colab.research.google.com/github/margazadasha/Machine-learning-ML/blob/main/%D0%9C%D0%B0%D1%80%D0%B3%D0%B0%D0%B7%D0%B0_4_6%D0%A4%D0%86%D0%A2_%D0%9F%D0%A0%E2%84%961_%D0%92%D0%B0%D1%80%D1%96%D0%B0%D0%BD%D1%82%2216.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Лабораторна робота №1.
Вступ до машинного навчання. Елементи лінійної алгебри.
# Варіант №16

In [ ]:
!pip install numpy

In [ ]:
import numpy as np
numpy_version = np.__version__
print(f"NumPy version: {numpy_version}")

NumPy version: 1.26.4


In [ ]:
#Завдання 1
#Створіть одновимірний масив (вектор) з найменшими непарними числами, не менше 15, та виведіть його значення.
import numpy as np
odd_nembers_array = np.arange(15, 35, 2)
print (odd_nembers_array)

[15 17 19 21 23 25 27 29 31 33]


In [ ]:
#Завдання 2
#Створіть двовимірний масив (матрицю), розміром 3х3, заповніть його значеннями випадкових дійсних чисел від 0 до одиниці.
import numpy as np
random_matrix = np.random.rand(3, 3)
print(random_matrix)

[[0.18973741 0.10256341 0.19335169]
 [0.94412369 0.44261312 0.49646154]
 [0.9075821  0.61758917 0.60302958]]


In [ ]:
#Завдання 3
#Створіть масив, розміром 3х3, заповніть його випадковими дійсними числами від 0 до одиниці та знайдіть мін. елемент.
import numpy as np
rand_matrix = np.random.rand(3, 3)
min_element = np.min(rand_matrix)

print("Масив 3x3 з випадковими дійсними числами:")
print(rand_matrix)
print("\nМінімальний елемент у масиві:", min_element)

Масив 3x3 з випадковими дійсними числами:
[[0.16368504 0.28401406 0.55336913]
 [0.18717247 0.56666741 0.6536959 ]
 [0.17916318 0.04390464 0.66831113]]

Мінімальний елемент у масиві: 0.043904638941878904


In [ ]:
#Завдання 4
#Створіть масив, розміром 3х3, заповніть його випадковими дійсними числами в діапазоні від 0 до 1 та знайдіть вектор-стовпчик,
#що містить мінімальні елементи в кожному рядку.
import numpy as np
matrix = np.random.rand(3, 3)

min_elements_vector = np.min(matrix, axis = 1)
min_elements_vector = min_elements_vector.reshape(-1, 1)

print("Масив 3x3 з випадковими дійсними числами:")
print(matrix)
print("\nВектор-стовпчик мінімальних елементів у кожному рядку:")
print(min_elements_vector)

Масив 3x3 з випадковими дійсними числами:
[[0.55213023 0.75901614 0.30510399]
 [0.69125609 0.28273091 0.85729865]
 [0.97341306 0.87278408 0.96291988]]

Вектор-стовпчик мінімальних елементів у кожному рядку:
[[0.30510399]
 [0.28273091]
 [0.87278408]]


In [ ]:
#Завдання 5
#Створіть два одновимірних масиви, розміром 4, заповніть їх випадковими цілими числами від -5 до 5 та виконайте на них
#поелементні операції додавання, віднімання та множення.
import numpy as np
array1 = np.random.randint(-5, 6, 4)
array2 = np.random.randint(-5, 6, 4)

sum_arrays = array1 + array2
difference_arrays = array1 - array2
product_arrays = array1 * array2

print("Перший масив:", array1)
print("Другий масив:", array2)

print("\nРезультат додавання:", sum_arrays)
print("Результат віднімання:", difference_arrays)
print("Результат множення:", product_arrays)

Перший масив: [ 1  2 -5  4]
Другий масив: [-4 -5  1  4]

Результат додавання: [-3 -3 -4  8]
Результат віднімання: [ 5  7 -6  0]
Результат множення: [ -4 -10  -5  16]


In [ ]:
#Завдання 6
#Створіть дві матриці 3х3, заповіть їх довільними цілими числами від 0 до 10 та знайдіть їх добуток.
import numpy as np
matrix1 = np.random.randint(10, size=(3,3))
matrix2 = np.random.randint(10, size=(3,3))
product_matrix = matrix1 * matrix2

print("Перша матриця:")
print(matrix1)
print("Друга матриця:")
print(matrix2)

print("\nРезультат множення:")
print(product_matrix)

Перша матриця:
[[1 5 7]
 [5 1 2]
 [8 4 8]]
Друга матриця:
[[5 1 2]
 [7 2 8]
 [7 6 3]]

Результат множення:
[[ 5  5 14]
 [35  2 16]
 [56 24 24]]


In [ ]:
#Завдання 7
#Створіть дві матриці, розмірами 2х3 та 3х3, заповніть їх випадковими цілими числами в діапазоні від 1 до 4 та перемножте їх між собою.
import numpy as np
matrix1 = np.random.randint(1, 5, (2, 3))
matrix2 = np.random.randint(1, 5, (3, 3))
result_matrix = np.dot(matrix1, matrix2)

print("Перша матриця:")
print(matrix1)
print("Друга матриця:")
print(matrix2)

print("\nРезультат множення:")
print(result_matrix)

Перша матриця:
[[3 4 2]
 [1 4 2]]
Друга матриця:
[[4 1 2]
 [2 1 3]
 [2 2 2]]

Результат множення:
[[24 11 22]
 [16  9 18]]


In [ ]:
#Завдання 8
#Створіть матрицю, розміром 3х3, заповніть її випадковими цілими числами в діапазоні від 1 до 12 та знайдіть її обернену матрицю.
matrix = np.random.randint(1, 13, (3, 3))
inverse_matrix = np.linalg.inv(matrix)

print("Початкова матриця (3x3):")
print(matrix)

print("\nОбернена матриця:")
print(inverse_matrix)

Початкова матриця (3x3):
[[ 5  3  8]
 [11  1  7]
 [ 3  4  2]]

Обернена матриця:
[[-0.13333333  0.13333333  0.06666667]
 [-0.00512821 -0.07179487  0.27179487]
 [ 0.21025641 -0.05641026 -0.14358974]]


In [ ]:
#Завдання 9
#Створіть матрицю, розміром 4х4, заповніть її випадковими цілими числами в діапазоні від -7 до 7 та транспонуйте її.
matrix = np.random.randint(-7, 8, (4, 4))
transposed_matrix = matrix.transpose()

print("Початкова матриця (4x4):")
print(matrix)

print("\nОбернена матриця:")
print(transposed_matrix)

print("Ще один спосіб транспонування матриці:")
print(matrix.T)

Початкова матриця (4x4):
[[-2  7 -7 -2]
 [ 3  6 -4 -6]
 [ 2 -3  3 -4]
 [-5  1 -4  5]]

Обернена матриця:
[[-2  3  2 -5]
 [ 7  6 -3  1]
 [-7 -4  3 -4]
 [-2 -6 -4  5]]
Ще один спосіб транспонування матриці:
[[-2  3  2 -5]
 [ 7  6 -3  1]
 [-7 -4  3 -4]
 [-2 -6 -4  5]]


In [ ]:
#Завдання 10
#Створіть матрицю, розміром 3х4, та вектор, розміром 4х1, заповніть матрицю випадковими дійсними числами від 0 до 1, а вектор -
#випадковими дійсними числами від 0 до 1, і знайдіть добуток матриці на вектор.
matrix = np.random.rand(3, 4)
vector = np.random.rand(4, 1)

result = np.dot(matrix, vector)

print("Матриця (3x4):")
print(matrix)

print("\nВектор (4x1):")
print(vector)

print("\nДобуток матриці на вектор:")
print(result)

Матриця (3x4):
[[0.99423306 0.38325597 0.3763015  0.42918832]
 [0.24951719 0.58327025 0.40415703 0.04812983]
 [0.43922669 0.78607068 0.73311727 0.84088541]]

Вектор (4x1):
[[0.90545714]
 [0.92169966]
 [0.92125888]
 [0.78659797]]

Добуток матриці на вектор:
[[1.93775208]
 [1.17371919]
 [2.45905157]]


In [ ]:
#Завдання 11
#Створіть матрицю, розміром 2х3, та вектор, розміром 3х1, заповніть матрицю випадковими дійсними числами від 0 до 1, а вектор -
#випадковими цілими числами від 1 до 10, і знайдіть добуток матриці на вектор.
matrix = np.random.rand(2, 3)
vector = np.random.randint(1, 11, (3, 1))

result = np.dot(matrix, vector)

print("Матриця (2x3):")
print(matrix)

print("\nВектор (3x1):")
print(vector)

print("\nДобуток матриці на вектор:")
print(result)

Матриця (2x3):
[[0.62387844 0.43706676 0.60472311]
 [0.01733543 0.90837216 0.87514618]]

Вектор (3x1):
[[3]
 [6]
 [2]]

Добуток матриці на вектор:
[[5.70348209]
 [7.25253159]]


In [ ]:
#Завдання 12
#Створіть дві матриці, розміром 9х9, заповніть їх випадковими цілими числами в діапазоні від 1 до 10 та знайдіть відношення елементів
#другого стовпця другої матриці до відповідних елементів першої матриці (поелементне ділення).
matrix1 = np.random.randint(1, 11, (9, 9))
matrix2 = np.random.randint(1, 11, (9, 9))

second_column_matrix2 = matrix2[:, 1]

result = second_column_matrix2[:, np.newaxis] / matrix1

print("Перша матриця (9x9):")
print(matrix1)

print("\nДруга матриця (9x9):")
print(matrix2)

print("\nВідношення елементів другого стовпця другої матриці до відповідних елементів першої матриці:")
print(result)

Перша матриця (9x9):
[[ 2  6  2  8  7  6 10  4  3]
 [ 8  5  4  5  8  2  2 10 10]
 [ 9  7 10  6  5  6  7  9  3]
 [ 5  8 10 10  1  1  6 10  3]
 [ 9 10  8  8  3  7  5  1  6]
 [ 7  6  2  6  7 10  7  1  2]
 [ 3  2  4  9  5  5 10  6  9]
 [ 2  2  1  1  1  7  4  6  8]
 [ 5  9 10  1  5 10  5  2  1]]

Друга матриця (9x9):
[[ 6  9  8  7  9 10  2  9  2]
 [ 5  5  4  1  8  3 10  1  4]
 [ 4  4  2  8  9  8  6 10  1]
 [ 6  2  3  6  4 10  2  1  7]
 [ 7  1  2  5  8  8  9  4  8]
 [ 5  4  3 10  1  2  4  5  4]
 [ 5  5  7  4  7  3  3  9  5]
 [ 2  4  2 10  8  6  4  3  9]
 [ 3  1  1  4  5  8  2  5  8]]

Відношення елементів другого стовпця другої матриці до відповідних елементів першої матриці:
[[4.5        1.5        4.5        1.125      1.28571429 1.5
  0.9        2.25       3.        ]
 [0.625      1.         1.25       1.         0.625      2.5
  2.5        0.5        0.5       ]
 [0.44444444 0.57142857 0.4        0.66666667 0.8        0.66666667
  0.57142857 0.44444444 1.33333333]
 [0.4        0.25      

In [ ]:
#Завдання 13
#Створіть дві матриці, розміром 3х3, заповніть їх випадковими цілими числами в діапазоні від 1 до 10 та знайдіть добуток їх елементів.
matrix1 = np.random.randint(1, 11, (3, 3))
matrix2 = np.random.randint(1, 11, (3, 3))

elementwise_product = matrix1 * matrix2

print("Перша матриця (3x3):")
print(matrix1)

print("\nДруга матриця (3x3):")
print(matrix2)

print("\nДобуток відповідних елементів матриць:")
print(elementwise_product)

Перша матриця (3x3):
[[ 9  5  8]
 [10  4 10]
 [ 4  2  8]]

Друга матриця (3x3):
[[6 8 2]
 [3 5 3]
 [4 2 8]]

Добуток відповідних елементів матриць:
[[54 40 16]
 [30 20 30]
 [16  4 64]]


In [ ]:
#Завдання 14
#Створіть матрицю, розміром 3х3, заповніть її випадковими цілими числами в діапазоні від 1 до 5 та знайдіть
#середнє геометричне значення елементів матриці.
matrix = np.random.randint(1, 6, (3, 3))

#Перетворення матриці в одномірний масив
matrix_flat = matrix.flatten()

#Обчислення середнього геометричного значення елементів матриці
geometric_mean = np.exp(np.mean(np.log(matrix_flat)))

print("Матриця (3x3):")
print(matrix)

print("\nСереднє геометричне значення елементів матриці:")
print(geometric_mean)

Матриця (3x3):
[[5 1 2]
 [3 2 2]
 [1 4 5]]

Середнє геометричне значення елементів матриці:
2.3745374686583927


In [ ]:
#Завдання 15
#Створіть матрицю, розміром 3х3, заповніть її випадковими дійсними числами в діапазоні від -2 до 2 та знайдіть вектор-стовпчик,
#що містить найменше за модулем ціле значення в кожному рядку матриці.
matrix = np.random.uniform(-2, 3, (3, 3))

#Округлення значення матриці до найближчих цілих чисел
matrix_rounded = np.round(matrix).astype(int)

#Пошук найменшого за модулем значення в кожному рядку
min_abs_values = np.apply_along_axis(lambda row: row[np.abs(row).argmin()], axis=1, arr=matrix_rounded)

#Перетворення у вектор-стовпчик
result_vector = min_abs_values.reshape(-1, 1)

print("Матриця (3x3) з дійсними числами:")
print(matrix)

print("\nОкруглена матриця (3x3):")
print(matrix_rounded)

print("\nВектор-стовпчик з найменшими за модулем значеннями в кожному рядку:")
print(result_vector)

Матриця (3x3) з дійсними числами:
[[ 0.27447421  1.07774905 -1.89541732]
 [ 1.01112799  1.48696508 -0.40199799]
 [ 2.216024    1.93624408  0.56858244]]

Округлена матриця (3x3):
[[ 0  1 -2]
 [ 1  1  0]
 [ 2  2  1]]

Вектор-стовпчик з найменшими за модулем значеннями в кожному рядку:
[[0]
 [0]
 [1]]


Висновок: В рамках даної лабораторної роботи було розглянуто основи лінійної алгебри та їх застосування в машинному навчанні з використанням Python. Ми розглянули створення та виконання різноманітних математичних операцій над матрицями та векторами за допомогою використання бібліотеки NumPy.

Таким чином, лабораторна робота продемонструвала важливість елементів лінійної алгебри в контексті машинного навчання і показала, як Python і бібліотека NumPy можуть спростити виконання математичних операцій та аналіз даних. Ці навички є основою для більш складних задач машинного навчання і аналізу даних.